export enum AccessLevel {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  INVESTIGATOR = 'INVESTIGATOR',
  STUDY_COORDINATOR = 'STUDY_COORDINATOR',
  CLINICAL_RESEARCH_ASSOCIATE = 'CLINICAL_RESEARCH_ASSOCIATE',
  MONITOR = 'MONITOR',
  DATA_ENTRY = 'DATA_ENTRY',
  VIEWER = 'VIEWER'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_APPROVAL = 'PENDING_APPROVAL'
}

export enum ComplianceRegion {
  INDIA = 'INDIA',
  GLOBAL = 'GLOBAL'
}
